### ISSUE TITLE
Transcript is empty when disfluencies is True

### ISSUE THREAD

**Issue by alexauvray** [AssemblyAI/assemblyai-python-sdk#70]
`aai.TranscriptionConfig(speaker_labels=True, language_code="fr", speakers_expected=speakers_qty, disfluencies=True)`

It's working fine when I remove the disfluencies parameter.

**Comment by m-ods** [comment]
Hey @alexauvray! The transcript is empty because our API returns an error for this request: disfluencies are not supported for French. Refer to our [Supported Languages page](https://www.assemblyai.com/docs/concepts/supported-languages) for more information.

I recommend that you include this in your code whenever you need to troubleshoot something:
```
print(transcript.id)
print(transcript.error)
```

Let me know if that helps! I'll close this issue for now!
